image: node:12.16.2-stretch

cache:
  paths:
    - node_modules/

test_async:
  script:
    - npm ci --only=production

deploy:
  stage: deploy
  script:
    - docker build -t registry.gitlab.com/jitenpatel7/node_discord_bot .
    - docker push registry.gitlab.com/jitenpatel7/node_discord_bot
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'